//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runner.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=gbk&quot; /&gt;
        ///		&lt;title&gt;自动化测试管理页面&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;form id=&quot;starttest&quot; method=&quot;post&quot; action=&quot;/StartTest&quot;&gt;
        ///			&lt;textarea rows=&quot;3&quot; cols=&quot;20&quot; id=&quot;bhs&quot; name=&quot;bhs&quot;&gt;&lt;/textarea&gt;
        ///		&lt;/form&gt;
        ///		&lt;a onclick=&quot;document.getElementById(&apos;starttest&apos;).submit(); return false;&quot; href=&apos;&apos;&gt;开始测试&lt;/a&gt;&lt;br&gt;&lt;br&gt;
        ///		&lt;a onclick=&quot;document.getElementById(&apos;stoptest&apos;).submit(); return false;&quot; href=&apos;&apos;&gt;结束测试&lt;/a&gt;&lt;br&gt;&lt;br&gt;
        ///		&lt;a onclick=&quot;document.getElementById(&apos; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=gbk&quot; /&gt;
        ///		&lt;title&gt;[title]&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;p&gt;
        ///			[message]
        ///		&lt;/p&gt;
        ///		&lt;div align=&quot;center&quot; style=&quot;z-index:999; position:fixed; bottom:60; right:0; border:1px solid #000; padding:4px; background:#ccc&quot; onclick=&quot;var h = document.documentElement.scrollHeight || document.body.scrollHeight; window.scrollTo(h,h);&quot;&gt;底　部&lt;/div&gt;
        ///		&lt;div align=&quot;center&quot; style=&quot;z-index:999; position:fixed; bottom:30; right:0; border:1px solid #000 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MessagePage {
            get {
                return ResourceManager.GetString("MessagePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=gbk&quot; /&gt;
        ///		&lt;title&gt;当前测试进度&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///		body
        ///			{
        ///				margin-left:auto;
        ///				margin-right:auto;
        ///				width:70%
        ///			}
        ///		
        ///		 #collectTable
        ///			{
        ///				margin:0 auto;
        ///				font-family:&quot;Trebuchet MS&quot;, Arial, Helvetica, sans-serif;
        ///			  width:90%;
        ///			  border-collapse:collapse;
        ///			}
        ///		#collectTable caption
        ///			{
        ///				font-size:1.5em;
        ///				color:dark;
        ///				padding:30px;
        ///				text-align:left;
        ///			}
        ///		
        ///		# [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SchedulePage {
            get {
                return ResourceManager.GetString("SchedulePage", resourceCulture);
            }
        }
    }
}
